# Address
sylius_admin_api_address:
    resource: |
        alias: sylius.address
        section: admin_api
        serialization_version: $version
        grid: sylius_admin_api_address
        form:
            options:
                customerField: true
    type: sylius.resource_api
    prefix: /v{version}

# TODO: We can remove this when issue is fixed:
# https://github.com/Sylius/Sylius/issues/9938
sylius_admin_api_order_index:
    resource: |
        alias: sylius.order
        section: admin_api_order
        only: [index]
        grid: sylius_admin_api_order
        serialization_version: $version
    type: sylius.resource_api
    prefix: /v{version}

# TODO: We can remove this when issue is fixed:
# https://github.com/Sylius/Sylius/issues/10024
# Currently we are overwriting the whole `product-attributes` API to add filter.
# Copied from following file:
# https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/product_attribute.yml#L4
sylius_admin_api_product_attribute:
    resource: |
        identifier: code
        alias: sylius.product_attribute
        section: admin_api
        except: ['create']
        serialization_version: $version
        criteria:
            code: $code
        grid: sylius_admin_api_product_attribute
    type: sylius.resource_api
    prefix: /v{version}

sylius_sulu_admin_api_authenticate:
    controller: SuluSyliusProducerPlugin:Authentication:authenticate
    path: v{version}/authenticate
    methods: [GET]

sylius_sulu_admin_api_verify:
    controller: SuluSyliusProducerPlugin:Verify:verify
    path: v{version}/verify/{token}
    methods: [PUT]
