framework:
    messenger:
        routing:
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\SynchronizeProductMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\SynchronizeProductVariantMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\RemoveProductMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\RemoveProductVariantMessage': sulu_sylius_transport
        serializer:
            enabled: true
    serializer:
        enabled: true
