framework:
    messenger:
        routing:
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\SynchronizeProductMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\SynchronizeProductVariantMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\SynchronizeTaxonMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\RemoveProductMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\RemoveProductVariantMessage': sulu_sylius_transport
            'Sulu\Bundle\SyliusConsumerBundle\Model\Product\Message\RemoveTaxonMessage': sulu_sylius_transport
        serializer:
            enabled: true
    serializer:
        enabled: true

sylius_grid:
    grids:
        sylius_admin_api_product_attribute:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product_attribute.class%"
            filters:
                code:
                    type: string
                    label: sylius.ui.code